### PR TITLE
Fixed issue #448, stars no longer interfere with username

### PR DESCRIPTION
**Pull request by AdnCodez**
Hi, @baltpeter I have fixed the issue of stars interfering with the username, I solved it using CSS Grid, kindly take a look at it and let me know 🙂

### CODE REVIEW

**Comment by AdnCodez** [comment]
Hi, @baltpeter any updates about this merge?

**Comment by AdnCodez** [comment]
Hi, @baltpeter any updates about this merge?

**Comment by baltpeter** [comment]
Hi @AdnCodez, thanks for the PR. :) I have assigned @zner0L for the review.

**Comment by zner0L** [comment]
Thank you for contributing and I am very sorry I only came around to reviewing this late! I am sorry, but it seems to me that your solution doesn't fit the way I would've like this to work and interferes with our "styling framework" with possible side-effects. Because of that, I will close this PR.

**Pull request closed without merging**
