### PR TITLE
Add Croatian translation

### PR DESCRIPTION
**Pull request by milotype**
Add Croatian translation with image

### CODE REVIEW

**Comment by mal-tee** [comment]
Thank you!

Not sure why this fails to build.
 @baltpeter,  seems like it can't find the link target at the bottom, do we have to rename that to "my-requests"? I really don't know why it can't find the image tho.

**Comment by baltpeter** [comment]
> @baltpeter, seems like it can't find the link target at the bottom, do we have to rename that to "my-requests"?

Exactly. `link` resolves the slug itself. You have to use the non-localized version (filename).

> I really don't know why it can't find the image tho.

Seems like something doesn't like non-ASCII filenames. :D

**Review by baltpeter — APPROVED** [review]
Thank you!

**Comment by milotype** [comment]
@baltpeter Thank you for making the necessary corrections ...

**Pull request merged**
