### PR TITLE
Fixed Bug: Changing the language #154

### PR DESCRIPTION
**Pull request by sohanpal**
There were 2 event listeners which causes to open modal 2 times.

### CODE REVIEW

**Comment by baltpeter** [comment]
Thanks for the PR!

@zner0L I believe there was a reason we added both event listeners. Do you remember why we did that?

**Comment by zner0L** [comment]
Yes, that is for a11y reasons. I don't remember the specifics but we might want that. Can you look into that @baltpeter?

**Comment by zner0L** [comment]
@baltpeter ?

**Comment by zner0L** [comment]
Actually, I think this is fine. `onBlur` is the important event and that is still implemented. Sorry it took so long…

**Comment by zner0L** [comment]
This is, however, a little counter intuitive because now you have to select the language and then click anywhere to blur the select. Still better than two popups, though. Smarter solutions are very welcome!

**Pull request merged**
