### PR TITLE
Update contributing details

### PR DESCRIPTION
**Pull request by baltpeter**

### CODE REVIEW

**Comment by baltpeter** [comment]
@zner0L I will merge this in a week if you don't object…

**Comment by NathanBnm** [comment]
I guess I'll have to update the corresponding French translation once it will be merged. I'm leaving this comment to be notified 😄

**Comment by baltpeter** [comment]
@NathanBnm I've invited you to the repo. Feel free to just push your changes to this branch.

**Comment by NathanBnm** [comment]
> 
> 
> @NathanBnm I've invited you to the repo. Feel free to just push your changes to this branch.

Thanks!

**Comment by NathanBnm** [comment]
I don't know if the German version should be `[satzung]({{< ref "verein/constitution" >}})` or `[satzung]({{< ref "verein/constitution" >}})`

**Pull request merged**
