### PR TITLE
Updates to JS packages, Hugo, Node and Yarn

### PR DESCRIPTION
**Pull request by baltpeter**
It's that time again…

This should be squashed.

### CODE REVIEW

**Comment by baltpeter** [comment]
Great, apparently the Docker image provided by Cypress themselves doesn't work… :D 

```
Error: Failed to launch the browser process!
/root/project/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
    at onClose (~/project/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at Interface.<anonymous> (~/project/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
error Command failed with exit code 1.
```

Guess, we'll leave that at the previous version then.

**Comment by zner0L** [comment]
Please review my changes, @baltpeter. I can't add you as a reviewer to your own PR apparently.

**Comment by baltpeter** [comment]
Will do. Let's see if the tests work this time…

**Comment by baltpeter** [comment]
Nope. :(

**Comment by zner0L** [comment]
As far as I can see this seems to work correctly. The only failed test is because of an old search config. Merge if you want, @baltpeter

**Comment by baltpeter** [comment]
Let's give it a go, I guess.

**Comment by baltpeter** [comment]
Awesome, seems to work now!

**Pull request merged**
