### PR TITLE
Fixes #823: Show language modal only where a translation exists

### LINKED ISSUE #823: Language suggestion message is also shown if no other languages are available
The `I18nWidget` only shows the languages for the _current_ page, not for the site as a whole.

Steps to reproduce:

1. Have browser language != DE.
2. Clear `country` cookie.
3. Visit https://www.datenanfragen.de/blog/e-mail-werbung-einwilligung-beschwerde/

image

### PR DESCRIPTION
**Pull request by davenewham**
…language matches current page availability

To Close #823

### CODE REVIEW

**Comment by davenewham** [comment]
Annoying - as these tests pass locally

**Review by zner0L — CHANGES_REQUESTED** [review]
I merged the current master into your changes and now the tests still fails and they also fail locally for me. You can ignore the fail in `svafinder.spec.js`, that is due to a problem with the backend at the time, but `use-cases/language-selection.spec.js` fails because of your changes. Can you fix the tests, @davenewham?

**Comment by davenewham** [comment]
Thanks @zner0L for trying that. It seems that the data structure had changed slightly since I last looked at this (for the better!)

**Review by zner0L — APPROVED** [review]
Thank you! Now it looks good :)

**Pull request merged**
