### PR TITLE
refocus search bar after selecting company

### LINKED ISSUE #435: Wizard: Re-focus search bar after selecting a company
In the wizard on our homepage, users can add companies through the search bar:

Peek 2020-10-10 14-47

When adding many companies (which is what the wizard is for, after all), it would be a lot more convenient if the search bar was re-focused after selecting a company.

### PR DESCRIPTION
**Pull request by sumirart**
fixes  #435 
thanks!

### CODE REVIEW

**Review by baltpeter — CHANGES_REQUESTED** [review]
Thanks for this PR! This works but I would prefer a different implementation that doesn't depend on the search bar being remounted.

I would suggest that we instead wrap `this.props.onAutocompleteSelected` in an anonymous function for the `autocomplete:selected` event and then call `.focus()` afterwards in that same function.

I my opinion that should also be more clear. What do you think?

**Comment by sumirart** [comment]
I think I have tried to do that but I got an error saying that `onAutocompleteSelected` is not a function.
But I will try again and inform you of the result.

Thanks!

**Comment by baltpeter** [comment]
If defined, `onAutocompleteSelected` should definitely be a function. This is where we are defining it for the wizard:

https://github.com/datenanfragen/website/blob/ce425600cca7111ba1bf187b165462f6536a3352/src/Components/Wizard.js#L138-L140

But I guess it's possible that it isn't defined. You should be able to get around that with a check like this:

https://github.com/datenanfragen/website/blob/ce425600cca7111ba1bf187b165462f6536a3352/src/Components/SearchBar.js#L129

**Comment by sumirart** [comment]
Okay, thank you for your explanation.
By the way, recently I always got error `fatal error: pipe failed` when running `hugo server`
Here is the complete log:
```
Start building sites … 

                   |  DE  |  EN  |  FR  |  PT   
-------------------+------+------+------+-------
  Pages            | 1808 | 1718 | 1667 | 1644  
  Paginator pages  |  169 |  164 |  161 |  161  
  Non-page files   |   30 |   23 |   11 |    5  
  Static files     | 1765 | 1765 | 1765 | 1765  
  Processed images |  188 |  104 |    5 |   22  
  Aliases          |  168 |   98 |   79 |   50  
  Sitemaps         |    1 |    1 |    1 |    1  
  Cleaned          |    0 |    0 |    0 |    0  

Built in 13103 ms
Watching for changes in /Users/sumirart/Dev/OPEN SOURCE/website/{assets,content,i18n,layouts,package.json,postcss.config.js,static}
Watching for config changes in /Users/sumirart/Dev/OPEN SOURCE/website/config/_default, /Users/sumirart/Dev/OPEN SOURCE/website/config/development
fatal error: pipe failed

goroutine 1 [running]:
runtime.throw(0x5ceb67e, 0xb)
        /usr/local/Cellar/go/1.15.2/libexec/src/runtime/panic.go:1116 +0x72 fp=0xc004387860 sp=0xc004387830 pc=0x403b392
runtime.sigNoteSetup(0x6e11ec0)
        /usr/local/Cellar/go/1.15.2/libexec/src/runtime/os_darwin.go:98 +0xc5 fp=0xc004387888 sp=0xc004387860 pc=0x40380e5
os/signal.signal_enable(0xad22a15e00000002)
        /usr/local/Cellar/go/1.15.2/libexec/src/runtime/sigqueue.go:198 +0xa5 fp=0xc0043878a8 sp=0xc004387888 pc=0x406fc65
os/signal.enableSignal(...)
        /usr/local/Cellar/go/1.15.2/libexec/src/os/signal/signal_unix.go:49
os/signal.Notify.func1(0x2)
        /usr/local/Cellar/go/1.15.2/libexec/src/os/signal/signal.go:144 +0x88 fp=0xc0043878c8 sp=0xc0043878a8 pc=0x55fe7e8
os/signal.Notify(0xc045543680, 0xc004387ae0, 0x2, 0x2)
        /usr/local/Cellar/go/1.15.2/libexec/src/os/signal/signal.go:164 +0x162 fp=0xc004387940 sp=0xc0043878c8 pc=0x55fe202
github.com/gohugoio/hugo/commands.(*commandeer).serve(0xc0009685b0, 0xc00050ae80, 0x6b, 0x80)
        /private/tmp/hugo-20201008-9797-1sectn3/hugo-0.76.3/src/github.com/gohugoio/hugo/commands/server.go:498 +0x625 fp=0xc004387b60 sp=0xc004387940 pc=0x5636ec5
github.com/gohugoio/hugo/commands.(*serverCmd).server(0xc00050ae80, 0xc0002e3b80, 0x6e118d8, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/hugo-20201008-9797-1sectn3/hugo-0.76.3/src/github.com/gohugoio/hugo/commands/server.go:274 +0x2b6 fp=0xc004387ca8 sp=0xc004387b60 pc=0x5635696
github.com/gohugoio/hugo/commands.(*serverCmd).server-fm(0xc0002e3b80, 0x6e118d8, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/hugo-20201008-9797-1sectn3/hugo-0.76.3/src/github.com/gohugoio/hugo/commands/server.go:131 +0x52 fp=0xc004387cf0 sp=0xc004387ca8 pc=0x5645af2
github.com/spf13/cobra.(*Command).execute(0xc0002e3b80, 0x6e118d8, 0x0, 0x0, 0xc0002e3b80, 0x6e118d8)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:838 +0x47c fp=0xc004387dc0 sp=0xc004387cf0 pc=0x41f8c1c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004262c0, 0xc0005069a0, 0x8, 0xc000263480)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x336 fp=0xc004387e98 sp=0xc004387dc0 pc=0x41f9756
github.com/gohugoio/hugo/commands.Execute(0xc00000e090, 0x1, 0x1, 0x400ac65, 0xc000108058, 0x0, 0x0)
        /private/tmp/hugo-20201008-9797-1sectn3/hugo-0.76.3/src/github.com/gohugoio/hugo/commands/hugo.go:90 +0xb9 fp=0xc004387f28 sp=0xc004387e98 pc=0x5622539
main.main()
        /private/tmp/hugo-20201008-9797-1sectn3/hugo-0.76.3/src/github.com/gohugoio/hugo/main.go:23 +0x76 fp=0xc004387f88 sp=0xc004387f28 pc=0x5647236
runtime.main()
        /usr/local/Cellar/go/1.15.2/libexec/src/runtime/proc.go:204 +0x209 fp=0xc004387fe0 sp=0xc004387f88 pc=0x403db69
runtime.goexit()
        /usr/local/Cellar/go/1.15.2/libexec/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc004387fe8 sp=0xc004387fe0 pc=0x4073a01

goroutine 35 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000373540)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:154 +0x105
created by go.opencensus.io/stats/view.init.0
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:32 +0x57

goroutine 7081 [syscall]:
syscall.syscall6(0x42389e0, 0x8, 0x0, 0x0, 0xc000abd688, 0xa, 0x6e11b90, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.15.2/libexec/src/runtime/sys_darwin.go:85 +0x2e
golang.org/x/sys/unix.kevent(0x8, 0x0, 0x0, 0xc000abd688, 0xa, 0x6e11b90, 0x0, 0x0, 0x0)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/golang.org/x/sys@v0.0.0-20200501145240-bc7a7d42d5c3/unix/zsyscall_darwin_amd64.go:292 +0xa6
golang.org/x/sys/unix.Kevent(0x8, 0x0, 0x0, 0x0, 0xc000abd688, 0xa, 0xa, 0x6e11b90, 0x0, 0x0, ...)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/golang.org/x/sys@v0.0.0-20200501145240-bc7a7d42d5c3/unix/syscall_bsd.go:413 +0x71
github.com/fsnotify/fsnotify.read(0x8, 0xc000abd688, 0xa, 0xa, 0x6e11b90, 0xc000abd688, 0x0, 0xa, 0x0, 0x0)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/kqueue.go:511 +0x6e
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc046f01440)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/kqueue.go:274 +0x831
created by github.com/fsnotify/fsnotify.NewWatcher
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/kqueue.go:62 +0x199

goroutine 7082 [select]:
github.com/gohugoio/hugo/watcher.(*Batcher).run(0xc047368d40)
        /private/tmp/hugo-20201008-9797-1sectn3/hugo-0.76.3/src/github.com/gohugoio/hugo/watcher/batcher.go:53 +0x174
created by github.com/gohugoio/hugo/watcher.New
        /private/tmp/hugo-20201008-9797-1sectn3/hugo-0.76.3/src/github.com/gohugoio/hugo/watcher/batcher.go:42 +0x125

goroutine 6999 [select]:
github.com/gohugoio/hugo/livereload.(*hub).run(0x6dd2440)
        /private/tmp/hugo-20201008-9797-1sectn3/hugo-0.76.3/src/github.com/gohugoio/hugo/livereload/hub.go:39 +0x1e9
created by github.com/gohugoio/hugo/livereload.Initialize
        /private/tmp/hugo-20201008-9797-1sectn3/hugo-0.76.3/src/github.com/gohugoio/hugo/livereload/livereload.go:98 +0x45

goroutine 6969 [select]:
github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1(0xc047368d40, 0xc0009685b0, 0xc0365dbfa8, 0xc047c7c360)
        /private/tmp/hugo-20201008-9797-1sectn3/hugo-0.76.3/src/github.com/gohugoio/hugo/commands/hugo.go:873 +0xe5
created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
        /private/tmp/hugo-20201008-9797-1sectn3/hugo-0.76.3/src/github.com/gohugoio/hugo/commands/hugo.go:871 +0x2ac
```

I'm using Mac Catalina, and I have been trying to reinstall Hugo and Go from my machine, running the command, even re-clone the repo. Do you have any idea how should I fix it?
Thank you.

**Comment by baltpeter** [comment]
Weird, we keep seeing this error on macOS. @chrysillala described a similar error in [this issue](https://github.com/datenanfragen/website/issues/367#issuecomment-706707886).

If the ideas I posted there don't work for you either, I think it would be best if you asked on the Hugo forum as I am unfortunately out of ideas. :/

**Comment by sumirart** [comment]
I solved it by running`hugo server --watch=false` (got from [this post](https://discourse.gohugo.io/t/hugo-is-crashing-upon-start-of-hugo-server-d-when-serving-a-lot-of-images/28540/18))

I create a new function which then calls `onAutocompleteSelected` (and `focus()`)because when declaring an anonymous function it cannot get props inside of it.
But now the problem is when I add a company the SearchBar also re-render, which also removes the focus afterwards.
What do you think?

**Comment by baltpeter** [comment]
Glad you found a solution to the problem with Hugo!

As for your question: Would you mind pushing a commit with your current changes, so I can take a look at them and use the Netlify deploy preview? Later, I'll squash the commits anyway, so the commit history will still stay clean.

**Comment by sumirart** [comment]
done, please check.

thank you!

**Comment by baltpeter** [comment]
Thanks! Not quite sure what to do in that case. :/ Maybe it's best if we revert to your original solution and just do the focus in `compontentDidMount`.

I'll ask @zner0L what he thinks.

**Comment by zner0L** [comment]
Thank you so much for your contribution! I am very sorry we left it lying around for so long. I finally refactored these changes in #645 and will therefore close this PR.

**Pull request closed without merging**
