### PR TITLE
Add Outlook Email URL in MailtoDropdown

### PR DESCRIPTION
**Pull request by galanggg**
Hello, I updated with the newest Outlook URL

### CODE REVIEW

**Comment by baltpeter** [comment]
Thanks for the PR. Unfortunately, the link doesn't seem to work. Whenever I click it, I get a server error:

Peek 2020-10-02 11-03

**Comment by baltpeter** [comment]
Also, `outlook.office.com` seems to only be for company accounts while `outlook.live.com` is for personal accounts. It seems more appropriate to support personal accounts for this purpose or what do you think?

**Comment by galanggg** [comment]
> Also, `outlook.office.com` seems to only be for company accounts while `outlook.live.com` is for personal accounts. It seems more appropriate to support personal accounts for this purpose or what do you think?

`https://outlook.live.com/mail/0/deeplink/compose?to=test@gmail.com&subject=test&body=testing` how about this one ? i test it in my url browser and it works, redirect to my Outlook

Screenshot from 2020-10-02 17-22-51

**Comment by baltpeter** [comment]
The test message you are using is very short. Have you tested it with our full email? As I have mentioned in the code comment, I think that is the problem.

**Comment by baltpeter** [comment]
@galanggg Are you still working on this?

**Pull request closed without merging**
