### PR TITLE
Fix banner images

### LINKED ISSUE #329: Broken image on act-page
https://www.datenanfragen.de/act/drk-brandenburg-datenleck/

The image https://www.datenanfragen.de/act/img/drk-brandenburg-datenleck.jpg doesn't load on my machine.

### PR DESCRIPTION
**Pull request by m-rey**
Fixes #329 

Some entries are listed on the [act](https://www.datenanfragen.de/act/) and [blog](https://www.datenanfragen.de/blog/) site with a thumbnail of
the featured image. Some of them also reference that banner image in
the metadata section of the entry, but the image itself is not shown
on the entry site.
All entries that reference the banner ("notice" section) in their
metadata should now have the correct banner image set.

### CODE REVIEW

**Comment by m-rey** [comment]
I like how the [blue banner images](https://github.com/datenanfragen/website/blob/master/content/de/blog/sample-letter-gdpr-direct-marketing-objection/musterbrief-dsgvo-werbewiderspruch.jpg) look like. How are they made? There are some blog entries where a banner and its thumbnail image would be fitting

**Comment by baltpeter** [comment]
Thanks for the quick PR, @m-rey! This works but I would like to ask you to switch to the shortcode we introduced in #292 (example is the last line from [here](https://github.com/datenanfragen/website/blob/eea138705a4607c238600bac365476c4025383a7/content/de/blog/supervisory-authorities/index.md)): 

```
 {{< img name="mahnung-senden" caption="Eine Beschwerde über Datenanfragen.de verschicken" alt="Screenshot des Anfragengenerators von Datenanfragen.de. Es wird eine Beschwerde an die Landesbeauftragte für den Datenschutz Niedersachsen über die Amazon Deutschland Services GmbH vorbereitet." >}}
```

This shortcode works whenever the image is in the same folder as the blog post (using [Hugo page resources](https://gohugo.io/content-management/page-resources/)).

This method has a number of benefits:

* We can simply reference the image by it's name and don't need to provide a full path anymore, hopefully avoiding problems like this in the future (Hugo complains about referencing page resources that don't exist, so the build will fail in that case).
* We can automatically apply post processing to optimize and resize the image (see #293 for a future use case).
* The shortcut 'forces' us to be more accessible by providing an alt text and (optionally) a caption.

I don't think this is documented anywhere, so sorry for the extra work. Proper documentation for stuff like this has been on our radar for a while now but we haven't gotten very far yet. :/

**Comment by baltpeter** [comment]
> I like how the [blue banner images](https://github.com/datenanfragen/website/blob/master/content/de/blog/sample-letter-gdpr-direct-marketing-objection/musterbrief-dsgvo-werbewiderspruch.jpg) look like. How are they made? There are some blog entries where a banner and its thumbnail image would be fitting

These are made using a Photoshop template I created. If you want, I can give you access to that. The template simply requires finding a good image from Unsplash, Pixabay et. al. and then tweaking some sliders until it looks good.  
I would love the have a free software version of this some day, using Gimp or Imagemagick for example, but currently our design resources are pretty dependent on Adobe software. :/

**Comment by baltpeter** [comment]
> I've seen that there are posts where the English and German entry share the same image. Like the hacktoberfest 2019 entry, where the image itself is only saved in `content/en/blog/hacktoberfest-2019`, but its german variant in `content/de/blog/hacktoberfest-2019` can also access the image. Is this because of the shortcode?

Exactly, Hugo page resources are shared between languages on posts with the same slug. As the shortcode uses those page resources (see [here](https://github.com/datenanfragen/website/blob/master/layouts/shortcodes/img.html) and [here](https://github.com/datenanfragen/website/blob/master/layouts/partials/functions/imgURL.html)), it can access the images from the other languages as well.

And as the Hacktoberfest image doesn't have any text to translate, we just 'recycled' the image.

**Pull request merged**
