### PR TITLE
Closes #566: Croatian translation

### LINKED ISSUE #566: Croatian translation
I'd like to add my Croatian translation on Weblate. I've translated it localy up to 98%, but I cannot upload the .po file on Weblate. Curretnly it's only possible to download files, but not to upload ... So please:

- enable file uploading on Weblate, or 
- if you don't want that, please add my attached file below.

Also, please add new source strings for **Croatian** language, similar to:
`msgctxt "i18n-widget.language-desc-de"` and `msgctxt "hugo.de"`

[datenanfragen-de-website-hr.po.zip](https://github.com/datenanfragen/website/files/6296878/datenanfragen-de-website-hr.po.zip)

### PR DESCRIPTION
**Pull request by baltpeter**

### CODE REVIEW

**Comment by baltpeter** [comment]
You're right. I didn't notice this on my machine (probably because I have Fira Sans installed and am not using the one from our server) but I was able to reproduce that in a virtual machine. I'll look into that.

**Comment by baltpeter** [comment]
@milotype I have now pulled in your latest changes from Weblate, added the sample letter posts and fixed the subsetting issue. Is there anything else you have noticed that we should change before launching the Croatian site? Otherwise, I think we're ready to go.

**Comment by milotype** [comment]
Great, most of it seems good … font issue seems solved … translation seem good ...

Issue 1:
Please, if possible, automate the process of adding contributors (translators/programmers) with links to their Weblate/GitHub accounts, to the page:
https://deploy-preview-568--datenanfragen.netlify.app/hr/open-source/#contributors

If you cannot automate the process, you could give some advice at https://github.com/datenanfragen/website/blob/master/AUTHORS on how to add ones name with link.


Issue 2:
There seems to be a problem with Croatian diacritics for uppercase letters in the menu for "Language" and "Country". The problem does not appear on the content of web pages ...




Thanks,
Milo

**Comment by baltpeter** [comment]
> Please, if possible, automate the process of adding contributors (translators/programmers) with links to their Weblate/GitHub accounts, to the page: deploy-preview-568--datenanfragen.netlify.app/hr/open-source/#contributors

We have decided against automatically listing people there as not everyone might want that. But that would have also been the next thing that I would have asked you. :) Feel free to either create a PR yourself or let me know if you want me to add you to the list, and if so with what name.

> If you cannot automate the process, you could give some advice at https://github.com/datenanfragen/website/blob/master/AUTHORS on how to add ones name with link.

The list is currently plain text only with no way of adding links. We had a brief discussion about adding more metadata in #231 but ultimately, we went with the current implementation as we didn't receive any more input.  
Personally, I would definitely prefer to keep not allowing links as we would then also have to decide which links are ok and which aren't (ads etc.).

> There seems to be a problem with Croatian diacritics for uppercase letters in the menu for "Language" and "Country". The problem does not appear on the content of web pages ...

Hm, not sure I can reproduce that. Here's what the menu looks like for me (on Windows, Ubuntu and macOS):

image

image

**Comment by milotype** [comment]
Yes, please add my name to the list:
Milo Ivir

BTW, the page https://deploy-preview-568--datenanfragen.netlify.app/hr/open-source/#contributors doesn't translate into Croatian. I did not find the appropriate text at Weblate. German page does translate! Hmmm ...

**Font issue:**
Ha, found it ... it seems to be a font display bug in my MacOS Firefox (and I don't think it can be corrected by some CSS properties).
Firefox

In MacOS Safari diacritics display correctly.
Safari

So, in general, you could regard the issue closed, as it seems to be OK from a **technical** point view.

But from a **typographical** point of view (and I'm a typographer ;-) ) there is a problem, which I don't know if it can be corrected. The font used in the dropdown menus is not _FiraGO_, but _Helvetica_ or some other sans-serif font. It is not specific to my Firefox/Safari ... your screenshot also show different fonts in the dropdown menues ;-(

If possible, correct it (I wouldn't know how to specify it in the CSS). Otherwise ignore it and launch the page.

Thank you for your help ...

**Comment by baltpeter** [comment]
> Yes, please add my name to the list:
> Milo Ivir

Done.

> BTW, the page [deploy-preview-568--datenanfragen.netlify.app/hr/open-source/#contributors](https://deploy-preview-568--datenanfragen.netlify.app/hr/open-source/#contributors) doesn't translate into Croatian. I did not find the appropriate text at Weblate. German page does translate! Hmmm ...

The text on pages like that is unfortunately not translatable through Weblate (that's what I meant [here](https://github.com/datenanfragen/website/issues/566#issuecomment-817990242)), they are [Markdown files](https://github.com/datenanfragen/website/pull/568/files#diff-121427a8334c641bcdc37cee901b59cb2fa4f55a2281f6d3974f56bbfff7568f) in this repository.

> **Font issue:**
> Ha, found it ... it seems to be a font display bug in my MacOS Firefox (and I don't think it can be corrected by some CSS properties).

Interesting. Here's what it looks like for me in Firefox on macOS (Catalina):

image

It's hard to say from your screenshot but it almost looks like the diacritics are being rendered but are cut off.

Either way, I would agree that this seems to be a Firefox bug that we unfortunately have no influence over. :( I would definitely also like to have this fixed but I'm afraid it's not possible to change the styling of the elements in the list.

**Comment by milotype** [comment]
> > Milo Ivir
> Done.

Thank you.

 > The text on pages like that is unfortunately not translatable through Weblate (that's what I meant [here](https://github.com/datenanfragen/website/issues/566#issuecomment-817990242)), they are [Markdown files](https://github.com/datenanfragen/website/pull/568/files#diff-121427a8334c641bcdc37cee901b59cb2fa4f55a2281f6d3974f56bbfff7568f) in this repository.

Please let me know if you have all data from my current fork. If so, I'd like to delete my current datenanfragen-fork and 
 fork it again, in order to translate those missing translations at https://github.com/datenanfragen/website/tree/b_croatian-translation/content/hr

> It's hard to say from your screenshot but it almost looks like the diacritics are being rendered but are cut off.

Yes, I also think they are just cut off in my Firefox on macOS El Capitan, which I cannot upgrade :-(

I'd suggest to ignore the font issue.

**Comment by baltpeter** [comment]
> Please let me know if you have all data from my current fork. If so, I'd like to delete my current datenanfragen-fork

Did you make any changes other than adding the templates? We have merged those into our `data` completely.

**Comment by milotype** [comment]
> Did you make any changes other than adding the templates? We have merged those into our `data` completely.

I don't think so ... But, if you have merged everything into your `data`, I would then delete and renew my fork, in order to translate those missing translations at https://github.com/datenanfragen/website/tree/b_croatian-translation/content/hr

Please let me know, which branch I should use (master, b-croatian-translation, or ...?)

So, from my point of view, the issues #568 as well as #566 could be closed now ...

Thank you again for all your help.

**Comment by baltpeter** [comment]
> I don't think so ... But, if you have merged everything into your `data`, I would then delete and renew my fork, in order to translate those missing translations at [https://github.com/datenanfragen/website/tree/b_croatian-translation/content/hr](https://github.com/datenanfragen/website/tree/b_croatian-translation/content/hr?rgh-link-date=2021-04-25T11%3A30%3A09Z)

Yep, we have merged that.

> Please let me know, which branch I should use (master, b-croatian-translation, or ...?)

I'll just merge this PR now and then you can work off of master. That's probably easiest.

> Thank you again for all your help.

Thank _you_ for all the work you're doing. :)

**Comment by baltpeter** [comment]
The current version of the site is now also live: https://www.osobnipodaci.org/

**Pull request merged**
