### PR TITLE
Add delete button for individual requests

### PR DESCRIPTION
**Pull request by xeluna**
#98 
Meine Anfragen · Datenanfragen de

For the object property name and the deletion confirmation messages, let me know if you would like them changed to something else. There probably is a better way to word the German version.

### CODE REVIEW

**Comment by baltpeter** [comment]
Deploy preview for *datenanfragen* ready!

Built with commit 2927da6e17bced54af1c8446a1a923c820543653

https://deploy-preview-123--datenanfragen.netlify.com

**Comment by xeluna** [comment]
Agh, I knew I forgot something. I've added the deletion from local storage.

**Comment by zner0L** [comment]
@baltpeter @xeluna I know that the issue was asking something different but why not just add another button similar to the existing one on the bottom? I mean, you can already select individual requests and export them, we just need a delete action as well.

**Comment by xeluna** [comment]
That's also another way to go about it. If that is what is preferred, I can change the implementation.

One reason I think for having the delete button inline is that the page has all the requests selected by default. This is a good default for exporting. But, for selection to delete, the user should have to select exactly what they want to avoid mistakenly deleting more than they intended.

For new users who are unfamiliar, there is the risk that they did not read the confirmation message correctly and end up deleting everything.

Of course this is from my own limited knowledge of how the website is used and I may be wrong.

**Comment by baltpeter** [comment]
@zner0L My original idea was having both features. I thought I had also created an issue for deleting multiple requests but apparently not.

You are raising a very valid point though, @xeluna. I hadn't considered that.

Either way, I think we should definitely have the option of deleting individual requests. Unless you are opposed to that, @zner0L, I will merge this.

**Pull request merged**
