### PR TITLE
TypeScriptify i18n functions and CommentsWidget

### PR DESCRIPTION
**Pull request by baltpeter**
See #868.

### CODE REVIEW

**Comment by baltpeter** [comment]
I've narrowed the Cypress error down to this line:

**Review by zner0L — CHANGES_REQUESTED** [review]
If you fix the tests and implement `useCallback`, this is fine.

**Comment by baltpeter** [comment]
> If I remove that, it works fine. Setting an empty `paths` in Cypress' `tsconfig.json` doesn't help. Hm…

It genuinely seems to be caused by the `paths` property and not by the `globals.ts` that introduces. The error occurs even with an entirely empty `globals.ts`. Weird…

**Comment by baltpeter** [comment]
Changing the filename from `globals.ts` to `globals.d.ts` seems to solve the problem. That is more correct anyway, as those files will only contain declarations, never implementations.

**Comment by baltpeter** [comment]
Btw: I tend to make nice, scoped commits. Please don't squash them.

**Review by zner0L — APPROVED** [review]
Excellent. Love seeing the typing come together.

**Pull request merged**
