### PR TITLE
added support for AOL webmailer

### PR DESCRIPTION
**Pull request by privateOmega**
For #402

### CODE REVIEW

**Comment by privateOmega** [comment]
@baltpeter PTAL

**Comment by baltpeter** [comment]
Thanks for the PR, @privateOmega. AOL is a good addition.

Unfortunately, all line breaks were lost when I tested the feature. This needs to be fixed before we can merge.

image

**Comment by privateOmega** [comment]
@baltpeter Sure I will take a look at it when I get some time. And will try to resolve it ASAP.

**Comment by privateOmega** [comment]
@baltpeter I guess this needs to be put on hold indefinitely.
I tried different types of line feed and carriage return URL encoding like %0A,%0D, %0D%0A etc, but nothing seems to work and I guess at AOL mail side, they have an issue in their function which decodes the URL component.

**Comment by baltpeter** [comment]
That's unfortunate. Thanks for trying, though! I have still applied the 'hacktoberfest-accepted' label for your effort. :)

**Comment by privateOmega** [comment]
@baltpeter Thanks a lot.

**Pull request closed without merging**
