### PR TITLE
Fix request language fallback

### PR DESCRIPTION
**Pull request by zner0L**

### CODE REVIEW

**Comment by baltpeter** [comment]
Haven't looked at this in depth yet, but we should really add a test to check that we don't regress on this bug. Do you want to add that, @zner0L?

**Comment by baltpeter** [comment]
Other than the missing test, this PR is approved.

**Comment by baltpeter** [comment]
@zner0L I'm really not a fan of disabling web security, so here's an alternative solution that instead relies on the fact that different tests may in fact have different origins. If you're OK with that, we can merge.

**Comment by zner0L** [comment]
Ok, I finally checked and rebased this. This seems to be working fine. I am happy with merging if the tests come around. Do you wanna do the honors, @baltpeter?

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
