### PR TITLE
Translate "Press" page into French

### PR DESCRIPTION
**Pull request by NathanBnm**
I was wondering where I could translate the "At this time there are no press releases in French." sentence.

### CODE REVIEW

**Comment by baltpeter** [comment]
> I was wondering where I could translate the "At this time there are no press releases in French." sentence.

This sentence is pulled in from the translation files. You have already translated it through Weblate. :D 

For reference, it's in `src/i18n/fr.json:721`:

https://github.com/datenanfragen/website/blob/master/src/i18n/fr.json#L721

**Comment by NathanBnm** [comment]
> 
> 
> > I was wondering where I could translate the "At this time there are no press releases in French." sentence.
> 
> This sentence is pulled in from the translation files. You have already translated it through Weblate. :D
> 
> For reference, it's in `src/i18n/fr.json:721`:
> 
> https://github.com/datenanfragen/website/blob/master/src/i18n/fr.json#L721

Well "anglais" should be replaced by "français" in the case 😄

**Comment by baltpeter** [comment]
> Well "anglais" should be replaced by "français" in the case smile
> Edit: Updated on Weblate

Didn't even notice that. Very good point. :D

**Comment by baltpeter** [comment]
Combined into #237.

**Pull request closed without merging**
