### PR TITLE
Add robots txt

### PR DESCRIPTION
**Pull request by dlemstra**
This PR adds a robots.txt file that disallows everything for the non-production environment. This is a bit different that suggested in #81 but it should still fix that issue.

### CODE REVIEW

**Comment by baltpeter** [comment]
Deploy preview for *datenanfragen* failed.

Built with commit 16db8b4936f0e2d1a0af476be08c14d4c07889dd

https://app.netlify.com/sites/datenanfragen/deploys/5da2dcf4ebe98d0007dccd24

**Comment by baltpeter** [comment]
Thank you for the PR. Unfortunately, we have learned from experience that a `robots.txt`. Is not enough. To quote [Google's help page](https://support.google.com/webmasters/answer/6062608?hl=en):

> If you want to block your page from search results, use another method such as password protection or a [noindex](https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag) directive.
> […]
> **If your web page is blocked with a robots.txt file**, it can still appear in search results, but the search result will not have a description and look [something like this](https://support.google.com/webmasters/answer/7489871).

**Comment by dlemstra** [comment]
Thanks for your response and making me learn something new. Will open up a new PR then to resolve this.

**Comment by baltpeter** [comment]
Sounds good, thank you!

**Pull request closed without merging**
