### PR TITLE
Deploy security.txt

### PR DESCRIPTION
**Pull request by mal-tee**
Just copy the SECURITY.md (for now).
(Untested)

### CODE REVIEW

**Comment by baltpeter** [comment]
Thanks, but isn't the idea behind security.txt to have the file in a [specific format](https://securitytxt.org/) instead of human-readable text?

Something like this (but signed, I can do that once we agree on the content):

```
Contact: mailto:vorstand@datenanfragen.de
Expires: 2025-12-31T23:59:00.000Z
Encryption: https://www.datenanfragen.de/pgp/3E2B296B.asc
Preferred-Languages: en, de
Canonical: https://www.datenanfragen.de/.well-known/security.txt
Policy: https://github.com/datenanfragen/website/blob/master/.github/SECURITY.md
```

We can also add some comments if we want.

Also, [according the RFC, it should be at `/.well-known/security.txt`](https://www.rfc-editor.org/rfc/rfc9116.html#name-location-of-the-securitytxt):

> For web-based services, organizations MUST place the "security.txt" file under the "/.well-known/" path, e.g., https://example.com/.well-known/security.txt as per [[RFC8615](https://www.rfc-editor.org/rfc/rfc9116.html#RFC8615)] of a domain name or IP address. For legacy compatibility, a "security.txt" file might be placed at the top-level path or redirect (as per [Section 6.4](https://www.rfc-editor.org/rfc/rfc7231#section-6.4) of [[RFC7231](https://www.rfc-editor.org/rfc/rfc9116.html#RFC7231)]) to the "security.txt" file under the "/.well-known/" path. If a "security.txt" file is present in both locations, the one in the "/.well-known/" path MUST be used.

But we can add an alias for `/security.txt` that redirects there.

**Comment by mal-tee** [comment]
Oh, I totally forgot about the specific format 🤦 Will fix this.

**Comment by mal-tee** [comment]
```
Contact: mailto:vorstand@datenanfragen.de
Expires: 2025-06-01T11:37:00.000Z
Encryption: https://www.datenanfragen.de/pgp/3E2B296B.asc
Acknowledgments: https://www.datarequests.org/open-source/#contributors
Preferred-Languages: en, de
Canonical: https://www.datenanfragen.de/.well-known/security.txt
Policy: https://github.com/datenanfragen/website/blob/master/.github/SECURITY.md
```

Can you sign this, add it to the PR and merge?

**Comment by baltpeter** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Contact: mailto:vorstand@datenanfragen.de
Expires: 2025-06-01T11:37:00.000Z
Encryption: https://www.datenanfragen.de/pgp/3E2B296B.asc
Acknowledgments: https://www.datarequests.org/open-source/#contributors
Preferred-Languages: en, de
Canonical: https://www.datenanfragen.de/.well-known/security.txt
Policy: https://github.com/datenanfragen/website/blob/master/.github/SECURITY.md
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEELnLqW93jFzBY1/h9oMHAEj4rKWsFAmSEZaQACgkQoMHAEj4r
KWuKRQ/6A6WzKWlopWgn5VKecibBYfUbUWdMC+aer1iA6wzWWEGWsIC5Yq/RDWb0
Bo3EwU4yNhQXT7RF3rqUpWhBwBDMDwOU25NHcluM4VcV9tgpauEAFbzdCj/9fmRg
BSFygausSWgv67yRADwFa0kgqi0pfikD/cHh50pq5TK/11UQZhOCdfCn0C4xtZYM
nUHrAAtqKmfShEStGElBcOlUhc88oky/opj9DroPthqHTqr3+12IAJbYqjqjU2Mj
8emCZu1UKIGRroFIwW5L6R/Nx/F/+gcSlDh5yHikSafYXpQ4yCnje7Uohz9TiSU+
NB49mOM82V858FDvWwNQ/6K7tBXNVdOZCWlGdlLW373Ak/1HSdF08j4sBEJi//jO
MQUulXO916nC0Q4vY7zKFttqSXFu/4EkgvvYd1EoRpTgBBrbiX7D9AbQJ0QeL6sS
PT+d1Mw3Z2D7ce7KEH4Nfazb9O/g/I6xNik7NEzLdp4qOCMr/qBM33mgIlLET9yv
tR7eDrLX14yqsHueFnQErBgBgIBm9X4M+prpANrUfowpP8B3q/vMRnWyHqeo2hX7
ppHq7dL9/sXvw8gO51V4iSaD8YfEkE3PkJhn8u56p7m+2Vg5uwm53vZteZoQv5oz
+6aiARwqCGMt+d48dqDhilWtWmaDUq4qV4DoAmgbZD9LcmnjSV0=
=T559
-----END PGP SIGNATURE-----
```

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
