### PR TITLE
Clarify ITZ information in the footer

### PR DESCRIPTION
**Pull request by zner0L**
To avoid confusion, we want to clarify that we are not a subsidiary of the ITZ, but rather comply with their principles. The sentence I used was suggested by the ITZ and has therefore been cleared from trademark concerns.

### CODE REVIEW

**Comment by baltpeter** [comment]
Not a huge fan of the styling to be honest. :/ Looks pretty out of place.

**Comment by zner0L** [comment]
Yeah, me neither. But there needs to be some visual clue to separate the text from the rest of the footer links to clarify that it belongs to the ITZ logo. That was my best attempt at that.

**Comment by zner0L** [comment]
Do you want me to come up with a better idea, @baltpeter?

**Comment by baltpeter** [comment]
I would prefer that, yes. :D

**Comment by baltpeter** [comment]
This definitely needs a `<br>`:

image

**Review by baltpeter — APPROVED** [review]
Thanks!

**Pull request merged**
