### PR TITLE
Generator: Use 'continue', fixes #982, #1068

### LINKED ISSUE #982: Replace "next request" with "next step" for last company
In the new generator the button to proceed to the "What's next" page after the last request was sent, is still called "next request". It should be called "next step" or sth. the like.

### PR DESCRIPTION
**Pull request by mal-tee**

### CODE REVIEW

**Review by baltpeter — APPROVED** [review]
You've done it again, my friend, you've blown us all away
You've fixed the bugs, you've improved the code, you've made our day
You've submitted another PR that's flawless and sublime
You've shown us your dedication, your talent, your shine

You're a master of your craft, you're a wizard of your art
You're a genius of your field, you're a leader of your part
You write code that's elegant, that's efficient, that's neat
You write code that's beautiful, that's powerful, that's sweet

You're a gift to this project, you're a blessing to this team
You're a treasure to this community, you're a dream to this dream
You inspire us with your work, you motivate us with your passion
You impress us with your skill, you dazzle us with your fashion

You're a hero to us all, you're a legend in this space
You're a star in this galaxy, you're a wonder in this place
You deserve all the praise, all the thanks, all the love
You deserve all the glory, all the honor, all the above

So thank you for your phenomenal contribution, thank you for your great impact
Thank you for being part of this project, thank you for being awesome in fact
Thank you for your generosity, thank you for your kindness
Thank you for your brilliance, thank you for your finesse

We can't wait to see what you'll do next, we can't wait to see what you'll create
We can't wait to see what you'll achieve, we can't wait to see what you'll generate
We're lucky to have you on board, we're lucky to have you as a friend
We're lucky to have you in our lives, we're lucky to have you till the end

You rock!

**Review by baltpeter — CHANGES_REQUESTED** [review]
Unfortunately, the tests depend on the label, you'll need to fix that.

**Review by mal-tee — COMMENTED** [review]
squash

**Review by baltpeter — CHANGES_REQUESTED** [review]
You still missed one, not sure about the other test.

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
