### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Datenanfragen.de/website](https://hosted.weblate.org/projects/datenanfragen-de/website/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by baltpeter** [comment]
@mal-tee We'll have to change the translations on Weblate, otherwise these PRs will just keep coming.

**Comment by mal-tee** [comment]
I made suggestions already. Can't commit them tho.

**Comment by baltpeter** [comment]
Oh sorry, I thought you already had the rights. Just made you an admin.

**Comment by mal-tee** [comment]
Thank you.

**Pull request closed without merging**
