### PR TITLE
Fix featured image in English 'direct markting objection' post

### PR DESCRIPTION
**Pull request by baltpeter**
The English site was displaying the Spanish image. That was because
we match the featured image by `*<featured_image>*`. The one for the
English post was called `sample-letter-gdpr-direct-marketing-objection`,
and the Spanish one `sample-letter-gdpr-direct-marketing-objection-es`.

So, when we specified `sample-letter-gdpr-direct-marketing-objection`
for `featured_image` in the English post, it matched both and just so
happened to match the Spanish one first.

### CODE REVIEW

**Review by mal-tee — CHANGES_REQUESTED** [review]
Now the spanish version has no image: https://deploy-preview-690--datenanfragen.netlify.app/es/blog/modelo-carta-objecion-marketing-directo-rgpd/

**Comment by mal-tee** [comment]
But the right thumbnail.

**Comment by baltpeter** [comment]
Yeah, it didn't have one in the first place. But sure, we can add one.

**Review by mal-tee — APPROVED** [review]
Thank you!

**Pull request merged**
