### PR TITLE
Scrolling on the company database page 

### LINKED ISSUE #357: Scrolling on the company database is broken for mobile
If you search for a term on the database, you might not be able to see all results, because you can not scroll. Instead of moving the view, the list of all companies in the background is moved.

In this example you can only see the first three results, instead of all five.

grafik

### PR DESCRIPTION
**Pull request by hadron43**
Fixes #357

### CODE REVIEW

**Comment by hadron43** [comment]
@mal-tee @zner0L Please review this pull request.

**Comment by zner0L** [comment]
This is not quite what I had in mind. Like I said in #357, there are two things that need to happen:

- [ ] proper overflow handling in the search autocomplete list
- [ ] exclude the text and the button from the stickyness (don't forget to look into adding proper margins in the scss)

**Comment by hadron43** [comment]
Okay. I'll try to fix this.

**Comment by zner0L** [comment]
I am closing this as it has been stale for quite a while.

**Pull request closed without merging**
