### PR TITLE
Re-add .nvmrc

### PR DESCRIPTION
**Pull request by baltpeter**
Why did we delete this again, @mal-tee?

### CODE REVIEW

**Comment by mal-tee** [comment]
To unclutter the root folder. We also assumed that we don't need it.

**Comment by baltpeter** [comment]
Well, we do indeed not need it for CI. But it is very helpful for local development.

**Comment by mal-tee** [comment]
Do you mind removing the .percy file? We haven't used percy in ages, right? And with doing so we cankeep the amounts of files in root the same. :D

**Comment by baltpeter** [comment]
> Do you mind removing the .percy file?

Oh, good catch. I missed that. #1013

**Review by mal-tee — APPROVED** [review]
We should upgrade our node version. :D

**Pull request merged**
