### PR TITLE
Croatian update 2021 10 04

### PR DESCRIPTION
**Pull request by milotype**

### CODE REVIEW

**Comment by baltpeter** [comment]
Thank you very much, @milotype! Are you still working on this branch? Otherwise, I'd take over and fix the build errors.

**Comment by milotype** [comment]
@baltpeter Yes, please fix the build errors! Thank you. I don't know what they are. Sorry for the extra work!

**Comment by baltpeter** [comment]
> @baltpeter Yes, please fix the build errors! Thank you. I don't know what they are. Sorry for the extra work!

No worries at all! This one's actually our fault: The template for the `/verein` page expected some other pages to exist in order to link to them. I've change the template to fall back to the English ones now.

**Review by baltpeter — APPROVED** [review]
Thanks again!

**Pull request merged**
